name: Unit Tests

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
  release:
    branches:
      - master
      
env:
  PROJECT: ${{ github.event.repository.name }}.xcodeproj
  SCHEME: ${{ github.event.repository.name }}


jobs:
  spm_build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
    steps:
      - name: Checkout to master
        uses: actions/checkout@v1
      - name: Build using SPM and Swift
        run: |
          swift build -v
      - name: Test using SPM and Swift
        run: |
          swift test -v
          
  xcodebuild_build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
          destination: ['platform=iOS Simulator,OS=13.4.1,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check environment variables
        run: |
         echo PROJECT: $PROJECT
         echo SCHEME: $SCHEME
      - name: Check xcodebuild version
        run: |
          xcodebuild -version
          type -a xcodebuild
      - name: Check xcode-select version
        run: |
          xcode-select -version
          type -a xcode-select
      - name: Clean xcodeproject
        run: |
          xcodebuild clean
      - name: Build xcodeproject
        run: |
          xcodebuild build -project $PROJECT -scheme $SCHEME CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Test
        run: |
          xcodebuild test -project $PROJECT -scheme $SCHEME -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
         
  upload_code_coverage:
    name: Code coverage # codecov.io
    runs-on: macOS-latest
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
      - name: Preapre code coverage report
        run: |
          xcodebuild -project $PROJECT -scheme $SCHEME -sdk iphonesimulator -destination "${destination}" build tests
      - name: Update code coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -J $SCHEME
        env:
         destination: ${{ matrix.destination }}
