name: website

on: push

jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check environment variables
        run: |
         echo "PROJECT: VersionKit.xcodeproj"
         echo "SCHEME: VersionKit"
      - name: Check gem version
        run: |
          gem -v
          type -a gem
      - name: Check bundle version
        run: |
          bundle -v
          type -a bundle
      - name: Check xcodebuild version
        run: |
          xcodebuild -version
          type -a xcodebuild
      - name: Check xcode-select version
        run: |
          xcode-select -version
          type -a xcode-select
      - name: Check xcodebuild comptability
        run: |
          xcodebuild clean
          xcodebuild build -project VersionKit.xcodeproj -scheme VersionKit CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Install jazzy
        run: |
          gem install jazzy
      - name: Check jazzy version
        run: |
          jazzy -version
          type -a jazzy
      - name: Where am i
        run: |
          ls
      - name: Generate docs using jazzy
        run: |
          jazzy --build-tool-arguments CODE_SIGN_IDENTITY=,CODE_SIGNING_REQUIRED=NO,CODE_SIGNING_ALLOWED=NO \
             --clean \
             --author Mohammadreza Koohkan \
             --author_url https://mohamadreza.codes/ \
             --output public \
             --module VersionKit \
             --theme apple
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT: ${{ secrets.PROJECT }}
          SCHEME: ${{ secrets.SCHEME }}
