name: website

on: push

jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check gem version
        run: |
          gem -v
          type -a gem
      - name: Check bundle version
        run: |
          bundle -v
          type -a bundle
      - name: Check xcodebuild version
        run: |
          xcodebuild -version
          type -a xcodebuild
      - name: Check xcode-select version
        run: |
          xcode-select -version
          type -a xcode-select
      - name: Install jazzy
        run: |
          gem install jazzy
      - name: Check jazzy version
        run: |
          jazzy -version
          type -a jazzy
      - name: Generate docs using jazzy
        run: |
          jazzy --clean --author Mohammadreza Koohkan --author_url https://mohamadreza.codes/ --xcodebuild-arguments -project,VersionKit.xcodeproj,-scheme,VersionKit --output public --module VersionKit
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
